// <auto-generated />
using System;
using ASPNETSEMED.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace ASPNETSEMED.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240611141137_AlooBD")]
    partial class AlooBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPNETSEMED.Models.AlooModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Escola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlInet>("Ip")
                        .HasColumnType("inet");

                    b.HasKey("Id");

                    b.ToTable("Aloo");
                });

            modelBuilder.Entity("ASPNETSEMED.Models.AnydeskModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Escola")
                        .HasColumnType("text");

                    b.Property<string>("Patrimonio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Anydesk");
                });

            modelBuilder.Entity("ASPNETSEMED.Models.EscolaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Circuito")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Escola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<NpgsqlInet?>("Ip")
                        .HasColumnType("inet");

                    b.Property<float?>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Lon")
                        .HasColumnType("real");

                    b.Property<string>("Ra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Escola");
                });

            modelBuilder.Entity("ASPNETSEMED.Models.ImpressoraModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<NpgsqlInet?>("Ip")
                        .HasColumnType("inet");

                    b.Property<string>("Localizacao")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Printpage")
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Impressora");
                });
#pragma warning restore 612, 618
        }
    }
}
